---
- name: Install etcd
  become: true
  apt:
    name: etcd
    state: present

- name: Configure etcd
  become: true
  template:
    src: etcd.conf.j2
    dest: /etc/default/etcd
  notify: restart etcd
